'use client';
import {useEffect,useRef,useState} from 'react';
import {type PassageRange} from '@/lib/domain/references';
import {hebrewPassage,hebrewSourceChapter,originalData,hebrewUrl,sourceUrl,readableRef,type HebrewIndex,type HebrewToken} from '@/lib/domain/original-languages';
import {SavedStudyLink} from './word-studies';

/** Source-numbered Hebrew in the shared passage study pane. */
export default function HebrewPassage({ranges,source}:{ranges:PassageRange[];source?:{code:string;chapter:number}}){
 const [data,setData]=useState<Awaited<ReturnType<typeof hebrewPassage>>|null>(null),[index,setIndex]=useState<HebrewIndex|null>(null),[morphs,setMorphs]=useState<Record<string,string>>({}),[error,setError]=useState('');
 const [chosen,setChosen]=useState(''),[interlinear,setInterlinear]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{let active=true;setData(null);setError('');setChosen(new URLSearchParams(location.search).get('hebrewToken')||'');setInterlinear(new URLSearchParams(location.search).get('hebrewView')==='analysis');Promise.all([source?hebrewSourceChapter(source.code,source.chapter):hebrewPassage(ranges),originalData<HebrewIndex>('hebrew-index.json'),originalData<{codes:Record<string,string>}>('morphology.json')]).then(([d,i,m])=>{if(active){setData(d);setIndex(i);setMorphs(m.codes)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[ranges,source?.code,source?.chapter]);
 const selected=data?.verses.flatMap(v=>v.tokens).find(t=>t.id===chosen);
 useEffect(()=>{if(selected){heading.current?.focus({preventScroll:true});if(matchMedia('(max-width:1099px)').matches)heading.current?.scrollIntoView({block:'center'})}},[selected]);
 function choose(token:HebrewToken){setChosen(token.id);const u=new URL(location.href);u.searchParams.set('hebrewToken',token.id);history.replaceState({},'',u.pathname+u.search)}
 function closeWord(){const id=chosen;setChosen('');const u=new URL(location.href);u.searchParams.delete('hebrewToken');history.replaceState({},'',u.pathname+u.search);requestAnimationFrame(()=>document.getElementById('hebrew-study-'+id)?.focus())}
 function view(value:boolean){setInterlinear(value);const u=new URL(location.href);if(value)u.searchParams.set('hebrewView','analysis');else u.searchParams.delete('hebrewView');history.replaceState({},'',u.pathname+u.search)}
 const mainReference = data?.verses.find(v=>v.tokens.some(t=>t.id===chosen))?.reference || data?.verses[0]?.reference;
 const details=selected&&<section className="word-detail" aria-label="Hebrew word details"><div className="study-controls"><h3 ref={heading} tabIndex={-1} className="hebrew-text" lang="he" dir="rtl">{selected.surface}</h3><button onClick={closeWord}>Close word</button></div><p>{selected.language} · OSHB analysis</p><dl><dt>Source word parts</dt><dd><bdi className="hebrew-text">{selected.sourceSurface}</bdi></dd><dt>Source lemma field</dt><dd>{selected.lemma||'Unavailable'}</dd><dt>Morphology</dt><dd>{selected.morph}<p>{morphs[selected.morph]||'A description for this source tag is not available.'}</p></dd></dl>{selected.keys.map(k=><p key={k}><a href={hebrewUrl(k,location.pathname+location.search)}>Explore {k} · {index?.lemmas.find(l=>l.key===k)?.count.toLocaleString()} occurrences →</a></p>)}{index?.articles.filter(a=>a.keys.some(k=>selected.keys.includes(k))).map(a=><div key={a.slug}><p>Ordinary Means commentary · {a.author}</p><SavedStudyLink url={a.url}>{a.transliteration} — {a.description}</SavedStudyLink></div>)}<p className="study-help">Source analysis and authored commentary are distinct. No English word alignment. General dictionary definitions and pronunciation guides are not included.</p></section>;
 return <section className="hebrew-passage" aria-label="Hebrew passage study" data-study-edition="Westminster Leningrad Codex · Hebrew / Aramaic"><div className="greek-introduction"><p><strong>Westminster Leningrad Codex</strong> · Hebrew / Aramaic</p><p className="study-help">Select a word for its morphology, occurrences and related studies. {source?'Hebrew source numbering is retained; matching chapter and verse numbers do not establish passage alignment.':'Source numbering is retained; the OSHB numbering catalogue locates the English reading context, not word alignment.'}</p></div><div className="interlinear-controls"><div className="interlinear-views" role="group" aria-label="Hebrew display"><button aria-pressed={!interlinear} onClick={()=>view(false)}>Hebrew text</button><button aria-pressed={interlinear} onClick={()=>view(true)}>Word analysis</button></div><p className="study-help">Word analysis shows source lemma keys and morphology beneath each word. English glosses are not available.</p></div>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">Loading Hebrew passage…</p>}{data?.missing.length!==0&&data&&<p className="notice">No mapped Hebrew reading context for: {data.missing.map(readableRef).join(', ')}. This does not mean the text is absent.</p>}
 {mainReference&&<p><a href={sourceUrl('WLC',mainReference.split('.')[0],Number(mainReference.split('.')[1]),Number(mainReference.split('.')[2]))}>Open Hebrew as the main view →</a></p>}
 <div className={`greek-workspace${selected?' has-word':''}`}><div className="greek-passages">{data?.verses.map(v=><section key={v.reference} className="greek-verse" data-sync-numbers={v.reference.split('.').slice(1).join(':')} data-sync-edition="WLC" data-sync-anchors={v.anchors.join(' ')}><h3>{readableRef(v.reference)} (WLC)</h3>{v.anchors.length>0&&<p className="study-help">English reading context: {v.anchors.map(readableRef).join(', ')}{v.partial?' · Partial source relationship':''}.</p>}<p className={interlinear?'hebrew-analysis-words':'hebrew-text hebrew-passage-text'} lang="he" dir="rtl">{v.parts.map((p,i)=>{const t=v.tokens.find(t=>t.id===p.token);return <span key={i}>{p.prefix}{t?<button id={'hebrew-study-'+t.id} className={`${interlinear?'interlinear-word':'greek-token hebrew-word'}${chosen===t.id?' chosen':''}`} aria-pressed={chosen===t.id} onClick={()=>choose(t)}><span className="hebrew-text">{p.text}</span>{interlinear&&<><span className="interlinear-extra" dir="ltr">{t.keys.join(' · ')||'Lemma unavailable'}</span><span className="interlinear-extra" dir="ltr">{t.morph}</span></>}</button>:p.text}</span>})}</p>{v.notes.length>0&&<details><summary>Source reading notes</summary>{v.notes.map((n,i)=><div key={i}><p>{n.kind}</p>{n.readings.length?n.readings.map((r,j)=><p key={j}>{r.type==='x-qere'?'Read (qere)':r.type}: <bdi className="hebrew-text">{r.text}</bdi></p>):<p dir="auto">{n.text.replaceAll('/','')}</p>}</div>)}</details>}</section>)}</div>{selected&&<aside className="greek-inspector hebrew-inspector">{details}</aside>}</div></section>;
}
