'use client';
import {useEffect,useState} from 'react';
import {researchLemmas,researchManifest,researchBookName,researchBookOrder,researchOccurrences,researchHighlights,sourceVerseUrl,type ResearchLemma,type ResearchHit,type ResearchBook} from '@/lib/domain/lxx-research';
import {researchResultUrl} from '@/lib/study-navigation';
import {address,passageUrl} from '@/lib/domain/references';
import {formatReference} from '@/lib/reading-display';
export default function LemmaExplorer({lemma,initialSide='lxx',edition='BSB',researchContext,onNavigate}:{lemma:string;initialSide?:'nt'|'lxx';edition?:string;researchContext?:string;onNavigate?:(url:string)=>void}) {
 const [entry,setEntry]=useState<ResearchLemma|null>(null),[meta,setMeta]=useState<ResearchBook[]>([]),[side,setSide]=useState(initialSide),[hits,setHits]=useState<ResearchHit[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[book,setBook]=useState(''),[page,setPage]=useState(1),[sourceOnly,setSourceOnly]=useState(false),[marked,setMarked]=useState<{tokenId:string;start:number;end:number}[]>([]),[highlightError,setHighlightError]=useState('');
 useEffect(()=>{let active=true;setEntry(null);setError('');setLoading(true);setSide(initialSide);Promise.all([researchLemmas(),researchManifest()]).then(([data,m])=>{if(active){const found=data.find(e=>e.lemma===lemma.normalize('NFC'));if(!found)throw Error('Lemma missing from index');setEntry(found);setMeta(m.books);}}).catch(()=>{if(active){setError('The lemma index could not be loaded. Missing data does not mean there are no occurrences.');setLoading(false);}});return()=>{active=false;};},[lemma,initialSide]);
 useEffect(()=>{if(!entry)return;let active=true;setHits([]);setBook('');setPage(1);setSourceOnly(false);setLoading(true);setError('');researchOccurrences(entry,side).then(value=>{if(active)setHits(value);}).catch(()=>{if(active)setError('Occurrences could not be loaded. This is a data error.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[entry,side]);
 const filtered=hits.filter(h=>(!book||h.sourceBook===book)&&(!sourceOnly||!h.anchor));const visible=filtered.slice((page-1)*20,page*20);
 useEffect(()=>{let active=true;setMarked([]);setHighlightError('');researchHighlights(visible,side).then(v=>{if(active)setMarked(v);}).catch(()=>{if(active)setHighlightError('Exact word highlighting could not be loaded; source snippets remain available.');});return()=>{active=false;};},[hits,book,page,side,sourceOnly]);
 const books=[...new Set(hits.map(h=>h.sourceBook))].sort((a,b)=>side==='nt'?address(`${a}.1.1`).book.order-address(`${b}.1.1`).book.order:researchBookOrder(a,b));
 return <section className="lemma-explorer" aria-label="Cross-Testament lemma exploration"><h4>Explore {lemma} across Greek sources</h4><div className="study-controls" role="group" aria-label="Greek occurrence source">{(['nt','lxx'] as const).map(s=><button key={s} aria-pressed={side===s} onClick={()=>setSide(s)}>{s==='nt'?'NT · Nestle 1904':'Septuagint · source collection'}{entry?` (${s==='nt'?entry.nt.reduce((n,r)=>n+r.count,0):entry.lxx?.count||0} occurrences)`:''}</button>)}</div>
 <p className="study-help">Exact NFC lemma identity. NT counts cover matched Nestle verses. Septuagint counts cover all 59 source texts, including separately labeled alternatives and unpaired verses; they are not counts in a single uniform edition. {entry?.lxx&&<>English-mapped: {entry.lxx.mapped} occurrences; source-only: {entry.lxx.sourceOnly} occurrences.</>} Zero means no indexed match within this coverage.</p>
 {loading&&<p role="status">Loading Greek occurrences…</p>}{error&&<p role="alert">{error}</p>}
 {!loading&&!error&&<><label>Filter by source book <select value={book} onChange={e=>{setBook(e.target.value);setPage(1);}}><option value="">All source books ({hits.length.toLocaleString('en-US')} occurrences)</option>{books.map(b=><option key={b} value={b}>{side==='nt'?address(`${b}.1.1`).book.name:(meta.find(x=>x.id===b)?researchBookName(meta.find(x=>x.id===b)!):b)} ({hits.filter(h=>h.sourceBook===b).length.toLocaleString('en-US')} occurrences)</option>)}</select></label>{side==='lxx'&&<label className="study-controls"><input type="checkbox" checked={sourceOnly} onChange={e=>{setSourceOnly(e.target.checked);setPage(1);}}/> Only verses without an English correspondence</label>}
 <p role="status">{filtered.length} occurrences in {new Set(filtered.map(h=>h.sourceRef)).size} source verses</p>{!filtered.length&&<p>No indexed occurrences match these source filters.</p>}{highlightError&&<p role="status">{highlightError}</p>}
 {visible.map(h=>{const m=marked.find(x=>x.tokenId===h.tokenId);const url=researchContext&&side==='lxx'?`${researchResultUrl(h.sourceRef,researchContext)}&token=${encodeURIComponent(h.tokenId)}`:h.anchor?`${passageUrl([{start:h.anchor,end:h.anchor}],side==='nt'?'N1904':edition)}&panel=greek&token=${encodeURIComponent(h.tokenId)}`:sourceVerseUrl(h.sourceRef,h.tokenId);return <p className="occurrence" key={h.tokenId}><a href={url} onClick={e=>{if(onNavigate&&!e.metaKey&&!e.ctrlKey&&!e.shiftKey&&!e.altKey){e.preventDefault();onNavigate(url);}}}>{h.sourceLabel||formatReference(h.sourceRef)} · {h.surface}</a><small className="occurrence-source">Source text: {side==='nt'?'Nestle 1904':meta.find(b=>b.id===h.sourceBook)?researchBookName(meta.find(b=>b.id===h.sourceBook)!):h.sourceBook} · {h.anchor?`English correspondence: ${formatReference(h.anchor)}`:'Source-only verse · no English correspondence'}</small><span lang="grc">{m?<>{h.text.slice(0,m.start)}<mark className="occurrence-match">{h.text.slice(m.start,m.end)}</mark>{h.text.slice(m.end)}</>:h.text}</span></p>;})}
 {!!filtered.length&&<nav className="chapter-nav" aria-label="Cross-Testament occurrence pages"><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous occurrences</button><span>Page {page} of {Math.ceil(filtered.length/20)}</span><button disabled={page*20>=filtered.length} onClick={()=>setPage(page+1)}>Next occurrences</button></nav>}</>}
 </section>;
}
