'use client';
import StudyPanel from './study-panel';
import SourceLanguageStudy from './source-language-study';
import {SavedStudyLink} from './word-studies';
import {useEffect,useRef,useState} from 'react';
import {Popover,PopoverTrigger,PopoverContent,PopoverTitle} from '@/components/ui/popover';
import {NativeSelect} from '@/components/ui/native-select';
import {books,resolveReference} from '@/lib/domain/references';
import {editions,getCorpus,type Segment} from '@/lib/domain/corpus';
import {writeClipboard} from '@/lib/clipboard';
import {sourceEditions,sourceManifest,sourceBook,sourceUrl,searchSource,originalData,englishContext,hebrewUrl,hebrewExplorerReturn,readableRef,type SourceEdition,type SourceManifest,type SourceBook,type HebrewAnalysis,type HebrewIndex} from '@/lib/domain/original-languages';
const noRanges:import('@/lib/domain/references').PassageRange[]=[];
export default function OriginalLanguageReader(){
 const compareTrigger=useRef<HTMLButtonElement>(null);
 const url=new URL(typeof location==='undefined'?'http://local/read/GEN/1?translation=WLC':location.href),edition:SourceEdition=url.searchParams.get('translation')==='CVUL'?'CVUL':'WLC',code=url.pathname.split('/')[2]||'GEN',chapter=Number(url.pathname.split('/')[3]||1),selected=Number(url.searchParams.get('verses')||0);
 const [manifest,setManifest]=useState<SourceManifest|null>(null),[book,setBook]=useState<SourceBook|null>(null),[analysis,setAnalysis]=useState<HebrewAnalysis|null>(null),[index,setIndex]=useState<HebrewIndex|null>(null),[morphs,setMorphs]=useState<Record<string,string>>({}),[word,setWord]=useState(url.searchParams.get('word')||''),[error,setError]=useState(''),[analysisError,setAnalysisError]=useState(''),[picker,setPicker]=useState(false),[pendingBook,setPendingBook]=useState(code),[pendingChapter,setPendingChapter]=useState(chapter),[query,setQuery]=useState(''),[hits,setHits]=useState<Awaited<ReturnType<typeof searchSource>>|null>(null),[searching,setSearching]=useState(false),[page,setPage]=useState(1),[size,setSize]=useState(21),[focus,setFocus]=useState(false),[status,setStatus]=useState(''),[notice,setNotice]=useState('');
 const [compare,setCompare]=useState(url.searchParams.get('parallel')==='1'||url.searchParams.get('panel')==='compare'),[english,setEnglish]=useState('BSB'),[englishQuery,setEnglishQuery]=useState(''),[englishSegments,setEnglishSegments]=useState<Segment[]>([]),[compareError,setCompareError]=useState(''),[compareLoading,setCompareLoading]=useState(false);
 useEffect(()=>{try{const n=Number(localStorage.getItem('afnt-text-size'));if(n>=18&&n<=32)setSize(n)}catch{}},[]);
 useEffect(()=>{document.body.classList.toggle('reader-focus-mode',focus);return()=>document.body.classList.remove('reader-focus-mode')},[focus]);
 useEffect(()=>{let active=true;Promise.all([sourceManifest(edition),sourceBook(edition,code),originalData<{text:string}>('notice.json')]).then(([m,b,n])=>{const ch=b.chapters.find(c=>c.chapter===chapter);if(!ch||selected&&!ch.verses.some(v=>v.verse===selected))throw Error('That source reference is not available in this edition.');if(active){setManifest(m);setBook(b);setNotice(n.text)}}).catch(e=>{if(active)setError(e.message)});
 if(edition==='WLC')Promise.all([originalData<HebrewAnalysis>(`analysis/${code}/${chapter}.json`),originalData<HebrewIndex>('hebrew-index.json'),originalData<{codes:Record<string,string>}>('morphology.json')]).then(([a,i,m])=>{if(active){setAnalysis(a);setIndex(i);setMorphs(m.codes)}}).catch(e=>{if(active)setAnalysisError(e.message)});return()=>{active=false}},[edition,code,chapter,selected]);
 const data=book?.chapters.find(c=>c.chapter===chapter),token=analysis?.verses.flatMap(v=>v.tokens).find(t=>t.id===word),name=books.find(b=>b.code===code)?.name||book?.name.replace(/\s*\(.*/, '')||code;
 useEffect(()=>{if(!data)return;const target=document.getElementById(selected?`source-verse-${selected}`:'reading');target?.focus({preventScroll:true});if(selected)target?.scrollIntoView({block:'center'})},[data,selected]);
 useEffect(()=>{if(!compare||!data||edition!=='WLC')return;let active=true;const refs=[...new Set((selected?data.verses.filter(v=>v.verse===selected):data.verses).flatMap(englishContext).map(r=>r.reference))];setCompareError('');setEnglishSegments([]);if(!refs.length){setCompareError('This source heading or verse has no numbered English reading context.');return}setCompareLoading(true);getCorpus(english).getPassage(refs.map(r=>({start:r,end:r}))).then(p=>{if(active)setEnglishSegments(p.segments)}).catch(e=>{if(active)setCompareError(e.message)}).finally(()=>{if(active)setCompareLoading(false)});return()=>{active=false}},[compare,data,selected,edition,english]);
 function go(b:string,c:number,v?:number){location.assign(sourceUrl(edition,b,c,v)+(compare?'&parallel=1':''))}
 useEffect(()=>{if(word){const panel=document.getElementById('hebrew-word-details');panel?.focus({preventScroll:true});if(matchMedia('(max-width:700px)').matches)panel?.scrollIntoView({block:'start'});}},[word,token?.id,data]);
 function selectWord(id:string){if(id&&compare){setCompare(false);const next=new URL(location.href);next.searchParams.delete('parallel');next.searchParams.delete('panel');history.replaceState({},'',next.pathname+next.search);}if(!id&&word)document.getElementById('hebrew-token-'+word)?.focus();setWord(id);const u=new URL(location.href);if(id)u.searchParams.set('word',id);else u.searchParams.delete('word');history.replaceState({},'',u.pathname+u.search)}
 function resize(n:number){setSize(n);try{localStorage.setItem('afnt-text-size',String(n))}catch{}}
 async function submit(){setError('');const ref=/^(.+?)\s+(\d+)(?::(\d+))?$/.exec(query.trim());if(ref&&manifest){const norm=(s:string)=>s.toLowerCase().replace(/[.\s]/g,'');const b=manifest.books.find(b=>[b.code,b.name,b.name.replace(/\s*\(.*/, ''),...(books.find(c=>c.code===b.code)?.aliases||[])].some(s=>norm(s)===norm(ref[1])));if(!b){setError('That book is not included in this edition.');return}try{const d=await sourceBook(edition,b.code),ch=d.chapters.find(c=>c.chapter===Number(ref[2]));if(!ch||ref[3]&&!ch.verses.some(v=>v.verse===Number(ref[3])))throw Error('That source reference is not available in this edition.');go(b.code,Number(ref[2]),ref[3]?Number(ref[3]):undefined)}catch(e){setError((e as Error).message)}return;}setSearching(true);setHits(null);setPage(1);try{setHits(await searchSource(edition,query))}catch(e){setError((e as Error).message)}finally{setSearching(false)}}
 async function manualEnglish(){setCompareError('');setEnglishSegments([]);setCompareLoading(true);try{const ranges=resolveReference(englishQuery);const p=await getCorpus(english).getPassage(ranges);setEnglishSegments(p.segments)}catch(e){setCompareError((e as Error).message)}finally{setCompareLoading(false)}}
 const order=manifest?.books.flatMap(b=>b.chapters.map(c=>({code:b.code,chapter:c})))||[],position=order.findIndex(p=>p.code===code&&p.chapter===chapter);
 const styles={fontSize:`${size/16}rem`};const tokenArticles=index?.articles.filter(a=>a.keys.some(k=>token?.keys.includes(k)))||[];
 return <><a className="skip" href="#reading">Skip to reading</a><header className="masthead"><a className="brand" href="/">Ad Fontes<span>A biblical study environment from Ordinary Means.</span></a><nav aria-label="Primary"><a className="active" href={sourceUrl(edition,code,chapter)}>Read</a><a href="/library">Library</a><a href="#original-source">Sources &amp; Editions</a><a href="/downloads">Downloads</a></nav><details className="mobile-nav"><summary>Menu</summary><nav aria-label="Mobile primary"><a href="/library">Library</a><a href="#original-source">Sources &amp; Editions</a><a href="/downloads">Downloads</a></nav></details></header>
 <div className="toolbar"><div className="passage-navigation"><button className="chapter-step" aria-label="Previous chapter" disabled={position<=0} onClick={()=>go(order[position-1].code,order[position-1].chapter)}>←</button><span className="toolbar-label">Passage</span><Popover open={picker} onOpenChange={open=>{setPicker(open);if(open){setPendingBook(code);setPendingChapter(chapter)}}}><PopoverTrigger className="passage-trigger">{name} {chapter} <span aria-hidden="true">⌄</span></PopoverTrigger><PopoverContent className="reader-popover" align="start"><PopoverTitle>Go to a passage</PopoverTitle><form onSubmit={e=>{e.preventDefault();go(pendingBook,pendingChapter)}}><div className="pickers"><label>Book<NativeSelect aria-label="Book" value={pendingBook} onChange={e=>{setPendingBook(e.target.value);setPendingChapter(1)}}>{manifest?.books.map(b=><option key={b.code} value={b.code}>{b.name}</option>)}</NativeSelect></label><label>Chapter<NativeSelect aria-label="Chapter" value={pendingChapter} onChange={e=>setPendingChapter(Number(e.target.value))}>{manifest?.books.find(b=>b.code===pendingBook)?.chapters.map(c=><option key={c}>{c}</option>)}</NativeSelect></label></div><button>OK</button></form></PopoverContent></Popover><button className="chapter-step" aria-label="Next chapter" disabled={position<0||position>=order.length-1} onClick={()=>go(order[position+1].code,order[position+1].chapter)}>→</button></div>
 <label className="edition-picker">Edition<NativeSelect aria-label="Edition" value={edition} onChange={async e=>{const target=e.target.value;try{let b='GEN';if(target==='WLC'||target==='CVUL'){const m=await sourceManifest(target);if(m.books.some(b=>b.code===code))b=code}else if(books.some(b=>b.code===code)&&(target!=='LXX2012'||books.slice(0,39).some(b=>b.code===code)))b=code;location.assign(`/read/${b}/1?translation=${target}`)}catch(e){setError((e as Error).message)}}}>{editions.filter(e=>e.language==='en').map(e=><option key={e.editionId} value={e.editionId}>{e.name}</option>)}<option value="LXX2012">LXX2012 · English Septuagint</option>{sourceEditions.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</NativeSelect></label><div className="toolbar-search unified-reader-search"><form className="passage-form" onSubmit={e=>{e.preventDefault();void submit()}}><label htmlFor="original-search">Go to a passage or search Scripture</label><div className="input-row"><input id="original-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={edition==='WLC'?'Job 1:1 or תם':'Genesis 1:1 or gratia'} required/><button disabled={searching}>Go</button></div></form></div></div>
 <main id="reading" tabIndex={-1} className={`reader-layout original-reader${compare?' has-study':word?' with-study':''}`}>
 {error&&<p role="alert">{error} <a href={sourceUrl(edition,'GEN')}>Open Genesis</a></p>}{!book&&!error&&<p role="status">Loading edition…</p>}{book&&data&&<>
 <div className="reader-tools"><div className="study-actions"><button ref={compareTrigger} className="study-tool" aria-pressed={compare} onClick={()=>{if(!compare&&new URL(location.href).searchParams.get('panel')==='hebrew'){const next=new URL(location.href);next.searchParams.set('panel','compare');next.searchParams.delete('parallel');location.assign(next.pathname+next.search);return;}setWord('');setCompare(!compare);const u=new URL(location.href);u.searchParams.delete('panel');u.searchParams.delete('word');if(!compare)u.searchParams.set('parallel','1');else u.searchParams.delete('parallel');history.replaceState({},'',u.pathname+u.search)}}><span className="tool-symbol" aria-hidden="true">Aa</span>Compare</button>{edition==='CVUL'&&<SourceLanguageStudy code={code} chapter={chapter} onOpen={()=>setCompare(false)}/>} {edition==='WLC'&&<a className="study-tool" href={hebrewUrl('',location.pathname+location.search)}>Hebrew Explorer</a>}<button className="study-tool focus-tool" aria-pressed={focus} onClick={()=>setFocus(!focus)}>{focus?'Exit focus':'Focus'}</button></div><Popover><PopoverTrigger className="settings-trigger" aria-label="Reading settings">Aa</PopoverTrigger><PopoverContent className="reader-popover" align="end"><PopoverTitle>Reading settings</PopoverTitle><p>Scripture text size</p><div className="type-size"><button aria-label="Decrease text size" disabled={size<=18} onClick={()=>resize(size-1)}>A−</button><output aria-label="Current text size">{size}</output><button aria-label="Increase text size" disabled={size>=32} onClick={()=>resize(size+1)}>A+</button></div></PopoverContent></Popover></div>
 {hebrewExplorerReturn(url.searchParams.get('explorer'))&&<p><a href={hebrewExplorerReturn(url.searchParams.get('explorer'))}>← Back to Hebrew Explorer results</a></p>}<div className="reader-selection-status"><p className="reader-hint">{selected?`Selected: ${name} ${chapter}:${selected}`:edition==='WLC'?'Select a Hebrew word to explore it, or a verse number to compare or copy.':'Select a verse number to copy it.'}</p>{selected>0&&<><button onClick={()=>go(code,chapter)}>Clear selection</button><button onClick={async()=>{try{await writeClipboard(`${name} ${chapter}:${selected} (${edition})\n${data.verses.find(v=>v.verse===selected)?.text}`);setStatus('Selection copied with reference.')}catch{setStatus('Could not copy; select the text to copy manually.')}}}>Copy selection</button></>}</div><p role="status">{status}</p>
 {searching&&<p role="status">Searching…</p>}{hits&&<section aria-label="Search results"><h2>{hits.length.toLocaleString()} matching source verses</h2>{edition==='WLC'&&<p className="study-help">Hebrew searches ignore vowel and cantillation marks; Scripture display remains unchanged.</p>}{hits.slice((page-1)*20,page*20).map(h=><p key={`${h.book}.${h.chapter}.${h.verse}`}><a href={sourceUrl(edition,h.book,h.chapter,h.verse)}>{manifest?.books.find(b=>b.code===h.book)?.name} {h.chapter}:{h.verse}</a> · <bdi lang={manifest?.language} className={edition==='WLC'?'hebrew-text':''}>{h.text}</bdi></p>)}<nav className="chapter-nav"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous results</button><span>Page {page}</span><button disabled={page*20>=hits.length} onClick={()=>setPage(page+1)}>Next results</button></nav></section>}
 <div className={word?'original-columns':'original-columns single'}><section className="chapter ot-chapter" aria-label="Source Scripture"><p className="ot-edition-disclosure">{edition==='WLC'?'Hebrew / Aramaic reading':'Historical Latin translation'} · Source numbering retained.</p><div className="chapter-heading"><p className="edition">{manifest?.name}</p><h1>{name} <span>{chapter}</span></h1></div><div className={`scripture${edition==='WLC'?' hebrew-scripture':''}`} lang={manifest?.language} dir={manifest?.direction} style={styles}>{data.verses.map(v=><div id={`source-verse-${v.verse}`} tabIndex={-1} className="source-verse" data-sync-numbers={`${chapter}:${v.verse}`} data-sync-anchors={edition==='WLC'?englishContext(v).map(r=>r.reference).join(' '):undefined} key={v.verse}><p className="text-block"><sup><a href={sourceUrl(edition,code,chapter,v.verse)+(compare?'&parallel=1':'')} aria-label={`${name} ${chapter}:${v.verse}`}>{v.verse}</a></sup>{v.parts.map((p,i)=><span key={i}>{p.prefix}{p.token&&analysis?<button id={'hebrew-token-'+p.token} className="hebrew-word" aria-pressed={word===p.token} onClick={()=>selectWord(p.token!)}>{p.text}</button>:p.text}</span>)}</p>{v.notes.length>0&&<details className="source-notes" dir="ltr"><summary>Source notes · {chapter}:{v.verse}</summary>{v.notes.map((n,i)=><div key={i}><strong>{n.kind==='variant'?'Reading variant':n.kind==='alternative'?'Alternative reading':'Source annotation'}</strong>{n.readings.length===0?<p dir="auto">{n.text.replaceAll('/','')}</p>:<p>The written form is retained in the verse; the source records this additional reading.</p>}{n.readings.map((r,j)=><p key={j}>{r.type==='x-qere'?'Read (qere)':r.type}: <bdi className="hebrew-text">{r.text}</bdi></p>)}</div>)}</details>}</div>)}</div></section>
 {word&&<aside className={word?'original-study with-word':'original-study'} aria-label="Original-language study">{word&&<section id="hebrew-word-details" tabIndex={-1} aria-label="Hebrew word details"><div className="study-controls"><h2>Hebrew word</h2><button onClick={()=>selectWord('')}>Close word</button></div>{analysisError&&<p role="alert">{analysisError}</p>}{token?<><h3 className="hebrew-text" dir="rtl">{token.surface}</h3><p>{token.language} · OSHB analysis</p><dl><dt>Source word parts</dt><dd><bdi className="hebrew-text">{token.sourceSurface}</bdi></dd><dt>Source lemma field</dt><dd>{token.lemma||'Unavailable'}</dd><dt>Morphology</dt><dd>{token.morph||'Unavailable'}<p>{morphs[token.morph]||'A description for this source tag is not available.'}</p></dd></dl>{token.keys.map(k=><p key={k}><a href={hebrewUrl(k,location.pathname+location.search)}>Explore {k} · {index?.lemmas.find(l=>l.key===k)?.count.toLocaleString()||'…'} occurrences →</a></p>)}{tokenArticles.length>0&&<><h3>Ordinary Means commentary</h3>{tokenArticles.map(a=><p key={a.slug}><SavedStudyLink url={a.url}>{a.transliteration} — {a.description}</SavedStudyLink><small> Larry Herzog Jr. · Read here</small></p>)}</>}<p className="study-help">Source analysis is distinct from Scripture and commentary. Occurrences follow written-text lemma keys; no English word alignment is implied.</p></>:<p role="status">{analysis?'This token is not present in the source chapter.':'Loading word analysis…'}</p>}</section>}
</aside>}</div>
 {compare&&<StudyPanel ranges={noRanges} mode="compare" edition={edition} source={{code,chapter,label:`${name} ${chapter}${selected?`:${selected}`:''}`,greek:false,syncAvailable:edition==='WLC',revision:`${english}-${compareLoading}-${englishSegments.length}`,comparison:(<section aria-label="English reading context"><h2>English reading context</h2><label>English edition<NativeSelect aria-label="English edition" value={english} onChange={e=>{setEnglish(e.target.value);setEnglishSegments([])}}>{editions.filter(e=>e.language==='en').map(e=><option value={e.editionId} key={e.editionId}>{e.name}</option>)}</NativeSelect></label>{edition==='WLC'?<p className="study-help">OSHB’s WLC-to-KJV numbering catalogue locates this English reading context. Partial relationships and numbered Hebrew headings can differ. This is not word alignment or a claim of identical text.</p>:<><p className="study-help">Choose an English passage independently. Vulgate numbering and textual boundaries differ; Sync by verse number is approximate; matching numbers may identify different passages.</p><form onSubmit={e=>{e.preventDefault();void manualEnglish()}}><label htmlFor="latin-english-reference">English passage</label><div className="input-row"><input id="latin-english-reference" value={englishQuery} onChange={e=>setEnglishQuery(e.target.value)} placeholder="Psalm 23 or John 1:1" required/><button>Read</button></div></form></>}{compareLoading&&<p role="status">Loading English…</p>}{compareError&&<p role="alert">{compareError}</p>}{englishSegments.map(s=><div key={s.id} data-sync-edition={english} data-sync-numbers={s.anchors.filter(r=>r.split('.')[0]===code).map(r=>r.split('.').slice(1).join(':')).join(' ')} data-sync-anchors={edition==='WLC'?s.anchors.join(' '):undefined}><a href={`/read/${s.anchors[0].split('.')[0]}/${s.anchors[0].split('.')[1]}?translation=${english}&verses=${s.anchors[0].split('.')[2]}`}>{readableRef(s.anchors[0])} →</a><p className="scripture" style={styles}>{s.text}</p></div>)}</section>)}} onClose={()=>{setCompare(false);const next=new URL(location.href);next.searchParams.delete('parallel');next.searchParams.delete('panel');history.replaceState({},'',next.pathname+next.search);requestAnimationFrame(()=>compareTrigger.current?.focus({preventScroll:true}));}}/>}

 {analysisError&&!word&&<p role="alert">Hebrew analysis unavailable: {analysisError}</p>}
 </>}
 <nav className="chapter-nav" aria-label="Source chapter navigation"><button disabled={position<=0} onClick={()=>go(order[position-1].code,order[position-1].chapter)}>← Previous chapter</button><button disabled={position<0||position>=order.length-1} onClick={()=>go(order[position+1].code,order[position+1].chapter)}>Next chapter →</button></nav><details id="original-source"><summary>About this edition and its sources</summary><p>{notice}</p><p>Original source numbering is retained. Edition changes open the beginning of the book when available, or Genesis otherwise. The Vulgate includes 73 supplied books, with Daniel’s and Esther’s additions; its appendix books are not included. Hebrew word analysis counts main written-text tokens separately from reading variants.</p><p><a href="https://github.com/openscriptures/morphhb" target="_blank" rel="noreferrer">OSHB source</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a> · <a href="https://la.wikisource.org/wiki/Vulgata_Clementina" target="_blank" rel="noreferrer">Clementine transcription</a></p></details>
 </main></>;
}
