'use client';
import { useEffect, useState } from 'react';
import { loadConnectionCatalog, connectionPairKey, connectionMatches, type TestamentConnection } from '@/lib/domain/testament-connections';
import { getCorpus, editions, type Segment } from '@/lib/domain/corpus';
import { isOtBook } from '@/lib/domain/ot-release';
import { address, passageUrl, type PassageRange } from '@/lib/domain/references';
import { formatPassage, formatReference } from '@/lib/reading-display';
import {comparisonRanges} from '@/lib/domain/greek-comparison';
import {connectedContextUrl} from '@/lib/study-navigation';
import PairedGreek from './paired-greek';
import {loadConnectionLabels,type ConnectionLabel} from '@/lib/domain/connection-labels';
export default function TestamentConnections({ranges, edition, embedded = false, onNavigate}: {ranges: PassageRange[]; edition: string; embedded?: boolean; onNavigate?: (url: string) => void}) {
  const [all,setAll]=useState<TestamentConnection[]>([]), [error,setError]=useState(''), [loaded,setLoaded]=useState(false);
  const [selected,setSelected]=useState<TestamentConnection|null>(null), [texts,setTexts]=useState<{ranges:PassageRange[];segments:Segment[]}[]>([]);
  const [labels,setLabels]=useState<ConnectionLabel[]>([]),[labelError,setLabelError]=useState(''),[labelsLoaded,setLabelsLoaded]=useState(false),[filter,setFilter]=useState('all');
  useEffect(()=>{let active=true;loadConnectionLabels().then(value=>{if(active){setLabels(value);setLabelsLoaded(true);}}).catch(()=>{if(active)setLabelError('Reviewed labels could not be loaded. Publisher references remain available.');});return()=>{active=false;};},[]);
  const selectedLabel=labels.find(l=>l.connectionIds.includes(selected?.id||''));
  const [selectionNotice,setSelectionNotice]=useState('');
  const [displayOrigin,setDisplayOrigin]=useState<'publisher'|'reviewed'|'manual'>('publisher');
  const [displaySides,setDisplaySides]=useState<PassageRange[][]|null>(null),[ntInput,setNtInput]=useState(''),[otInput,setOtInput]=useState(''),[rangeError,setRangeError]=useState('');
  useEffect(()=>{setDisplaySides(null);setDisplayOrigin('publisher');setRangeError('');if(selected){const publisher=new URL(location.href).searchParams.get('display')==='publisher';const sides=!publisher&&selectedLabel?.displayNtRanges?[selectedLabel.displayNtRanges,selectedLabel.otRanges]:[selected.sourceRanges,selected.targetRanges];if(!publisher&&selectedLabel?.displayNtRanges){setDisplaySides(sides);setDisplayOrigin('reviewed');}setNtInput(formatPassage(sides.find(rs=>!isOtBook(address(rs[0].start).book.code))!));setOtInput(formatPassage(sides.find(rs=>isOtBook(address(rs[0].start).book.code))!));const u=new URL(location.href);if(u.searchParams.has('ntDisplay')&&u.searchParams.has('otDisplay')){try{const nt=u.searchParams.get('ntDisplay')!,ot=u.searchParams.get('otDisplay')!;setDisplaySides([comparisonRanges(nt,false),comparisonRanges(ot,true)]);setDisplayOrigin('manual');setNtInput(nt);setOtInput(ot);}catch(e){setRangeError((e as Error).message);}}}},[selected,selectedLabel?.id]);
  const [view,setView]=useState<'english'|'greek'|'both'>('both');
  useEffect(()=>{const value=new URL(location.href).searchParams.get('connectionView');if(value==='english'||value==='greek'||value==='both')setView(value);},[]);
  const [textError,setTextError]=useState(''), [reading,setReading]=useState(false);
  const selectedEdition=editions.find(e=>e.editionId===edition)?.language==='en' ? edition : 'BSB';
  useEffect(()=>{let active=true; loadConnectionCatalog().then(index=>{if(active){setAll(index.connections);setLoaded(true);}}).catch(()=>{if(active)setError('NT/OT connections could not be loaded. This is a data error, not an absence of connections.');});return()=>{active=false;};},[]);
  const matches=all.filter(c=>connectionMatches(c,ranges) && (filter==='all' || (filter==='unclassified' ? !labels.some(l=>l.connectionIds.includes(c.id)) : labels.some(l=>l.connectionIds.includes(c.id)&&l.kind===filter))));
  useEffect(()=>{setSelected(null);setTexts([]);},[JSON.stringify(ranges)]);
  useEffect(()=>{if(embedded && all.length){const id=new URL(location.href).searchParams.get('connection');const requested=all.find(c=>c.id===id&&connectionMatches(c,ranges));setSelectionNotice(id&&!requested?'That connection is unavailable for this passage; showing another indexed connection when available.':'');setSelected(requested || all.find(c=>connectionMatches(c,ranges)) || null);}},[all,JSON.stringify(ranges),embedded]);
  useEffect(()=>{if(!selected)return;let active=true;setReading(true);setTextError('');setTexts([]);
    const sides=displaySides||[selected.sourceRanges,selected.targetRanges];
    Promise.all(sides.map(async rs=>({ranges:rs,segments:(await getCorpus(selectedEdition).getPassage(rs)).segments})))
      .then(value=>{if(active)setTexts(value);}).catch(()=>{if(active)setTextError('The connected passage could not be loaded. Try again or open its reading link.');}).finally(()=>{if(active)setReading(false);});
    return()=>{active=false;};
  },[selected,selectedEdition,JSON.stringify(displaySides)]);
  // Deduplicate navigation targets while retaining each original publisher citation in details.
  const groups=new Map<string,TestamentConnection[]>();
  for(const c of matches){const key=connectionPairKey(c);groups.set(key,[...(groups.get(key)||[]),c]);}
  const selectedGroupIndex=[...groups.values()].findIndex(cs=>cs.some(c=>c.id===selected?.id));
  const selectedPair=selected?[selected.sourceRanges,selected.targetRanges].sort((a,b)=>Number(isOtBook(address(a[0].start).book.code))-Number(isOtBook(address(b[0].start).book.code))):[];
  const connectionList = <ul className="connection-list">{[...groups.values()].map(cs=>{const c=cs[0];return <li key={c.id}>
      <button aria-pressed={!!selected&&cs.some(x=>x.id===selected.id)} onClick={()=>{setSelected(c);setSelectionNotice('');if(embedded){const url=new URL(location.href);url.searchParams.set('connection',c.id);url.searchParams.delete('ntDisplay');url.searchParams.delete('otDisplay');url.searchParams.delete('display');history.replaceState({},'',url.pathname+url.search);}if(embedded)requestAnimationFrame(()=>document.querySelector<HTMLElement>('.study-dialog .connected-passages h2')?.focus());}}>{formatPassage(c.sourceRanges)} ↔ {formatPassage(c.targetRanges)} · {labels.find(l=>l.connectionIds.includes(c.id))?.kind || 'Publisher reference'}</button><small className="connection-anchor-label">Publisher {c.kind==='publisher-heading-reference'?'heading':'note'} at {formatPassage(c.sourceRanges)} · {c.sourceEdition}</small>
      <details><summary>Publisher citation{cs.length>1?'s':''}</summary>{cs.map(item=><div key={item.id}><p>{item.publisherNote}</p><small>{item.sourceEdition} · {item.sourceRelease} · {item.noteId}</small></div>)}</details>
    </li>;})}</ul>;
  const currentOt = isOtBook(address(ranges[0].start).book.code);
  const orderedTexts = embedded ? [...texts].sort((a,b)=>Number(isOtBook(address(a.ranges[0].start).book.code)===currentOt)-Number(isOtBook(address(b.ranges[0].start).book.code)===currentOt)) : texts;
  const content = <>
    {labelError&&<p role="alert">{labelError}</p>}
    {labelsLoaded&&labels.length===0&&!labelError&&<p className="study-help">No classifications have been approved for publication yet. Publisher links remain available under All publisher references.</p>}
    {!loaded && !error && <p role="status">Loading connections…</p>}{error && <p role="alert">{error}</p>}
    {loaded && !groups.size && <p>{filter==='all'?'No indexed publisher cross-reference overlaps this selection.':'No approved connections match this filter and selection.'} This index covers explicit reference objects in BSB and MSB notes and headings; it is not a complete account of the NT’s use of the OT.</p>}
    {selectionNotice&&<p role="status">{selectionNotice}</p>}{embedded&&(groups.size>0||selected)&&<details className="connection-chooser"><summary>{selected?`Connection ${selectedGroupIndex>=0?`${selectedGroupIndex+1} of ${groups.size}`:'outside current filter'}: ${formatPassage(selectedPair[0])} ↔ ${formatPassage(selectedPair[1])}`:`Choose a connection (${groups.size})`}</summary>{connectionList}</details>}{!embedded&&connectionList}
    {selected && <section className="connected-passages" aria-label="Connected passages">
      <h2 tabIndex={-1}>Read the connected passages</h2><p className="selection-state" role="status">Display: <strong>{displayOrigin==='reviewed'?'Reviewed quotation':displayOrigin==='manual'?'Your selection':'Publisher passages'}</strong> · {selectedEdition}<small className="connection-display-anchor">Publisher anchor: {formatPassage(selected.sourceRanges)} ({selected.sourceEdition}); display span shown below.</small></p><div className="study-controls connections-display-controls" role="group" aria-label="Connected passage display">{(['english','greek','both'] as const).map(v=><button key={v} aria-pressed={view===v} onClick={()=>{setView(v);if(embedded){const url=new URL(location.href);url.searchParams.set('connectionView',v);history.replaceState({},'',url.pathname+url.search);}}}>{v==='english'?'English':v==='greek'?'Greek':'English and Greek'}</button>)}</div>
<details className="connection-settings"><summary>Connection details, filters and passage adjustments</summary>    <details className="connection-about"><summary>About these references</summary><p className="study-help">Cross-references from Berean Standard Bible and Majority Standard Bible publisher notes and explicitly marked headings, shown in both directions. Publisher references alone do not establish quotation, allusion or parallel classifications; approved editorial labels are shown separately. An anchor identifies the verse carrying a note or opening a heading; it does not establish quotation extent. Other editions retain their own wording.</p></details>
    <label>Connection type <select disabled={!labelsLoaded} value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">All publisher references</option><option value="quotation">Reviewed quotations</option><option value="allusion">Reviewed allusions</option><option value="parallel">Reviewed broader parallels</option><option value="unclassified">Unclassified publisher references</option></select></label>
<p>{selected.kind==='publisher-heading-reference'?'Publisher heading opening anchor:':'Publisher note anchor:'} {formatPassage(selected.sourceRanges)} ({selected.sourceEdition}). Reading: {selectedEdition}. The anchor does not establish quotation extent.</p>      {labels.filter(l=>l.connectionIds.includes(selected.id)).map(l=><details key={l.id}><summary>Reviewed {l.kind} · evidence and scope</summary><p>{l.sourceObservation}</p><p>Editorial judgment: {l.interpretation}</p><h4>Reviewed source evidence · BSB</h4>{l.evidence.map((e,i)=><blockquote key={i}><p>{e.text}</p><footer>{e.sourceRef} · {e.releaseId}</footer></blockquote>)}<p>Observation author: {l.author}. Reviewed by Larry Herzog Jr. · {l.approval.reviewedAt}</p><small>Approval hash: {l.approval.contentHash}</small></details>)}
      <details className="adjust-passages"><summary>Adjust passages</summary><form className="comparison-ranges" onSubmit={e=>{e.preventDefault();try{setDisplaySides([comparisonRanges(ntInput,false),comparisonRanges(otInput,true)]);setDisplayOrigin('manual');const u=new URL(location.href);u.searchParams.set('display','manual');u.searchParams.set('ntDisplay',ntInput);u.searchParams.set('otDisplay',otInput);history.replaceState({},'',u.pathname+u.search);setRangeError('');}catch(e){setRangeError((e as Error).message);}}}><label>NT display passage <input value={ntInput} onChange={e=>setNtInput(e.target.value)}/></label><label>OT display passage <input value={otInput} onChange={e=>setOtInput(e.target.value)}/></label><button type="submit">Compare these passages</button><button type="button" aria-pressed={displayOrigin==='publisher'} disabled={displayOrigin==='publisher'} onClick={()=>{setDisplaySides(null);setDisplayOrigin('publisher');setRangeError('');const u=new URL(location.href);u.searchParams.delete('ntDisplay');u.searchParams.delete('otDisplay');u.searchParams.set('display','publisher');history.replaceState({},'',u.pathname+u.search);const sides=[selected.sourceRanges,selected.targetRanges];setNtInput(formatPassage(sides.find(rs=>!isOtBook(address(rs[0].start).book.code))!));setOtInput(formatPassage(sides.find(rs=>isOtBook(address(rs[0].start).book.code))!));}}>Restore publisher passages</button>{selectedLabel?.displayNtRanges&&<button type="button" aria-pressed={displayOrigin==='reviewed'} disabled={displayOrigin==='reviewed'} onClick={()=>{setDisplaySides([selectedLabel.displayNtRanges!,selectedLabel.otRanges]);setDisplayOrigin('reviewed');setNtInput(formatPassage(selectedLabel.displayNtRanges!));setOtInput(formatPassage(selectedLabel.otRanges));setRangeError('');const u=new URL(location.href);u.searchParams.delete('ntDisplay');u.searchParams.delete('otDisplay');u.searchParams.delete('display');history.replaceState({},'',u.pathname+u.search);}}>Use reviewed quotation selection</button>}</form></details>{rangeError&&<p role="alert">{rangeError}</p>}</details>
      {reading && <p role="status">Loading passages…</p>}{textError && <p role="alert">{textError}</p>}
      {view!=='greek' && orderedTexts.map((side,i)=><article key={i}><h3>{isOtBook(address(side.ranges[0].start).book.code)?'Old Testament':'New Testament'} · {formatPassage(side.ranges)}</h3><div className="connected-english-verses">{side.segments.map(segment=><p key={segment.id}><span className="connected-verse-marker">{segment.anchors.map(formatReference).join('–')}</span>{' '}{segment.text}</p>)}</div><a href={connectedContextUrl(side.ranges,selectedEdition,selected.id,view,typeof location==='undefined'?'http://local':location.href)} onClick={event=>{if(!onNavigate || event.button!==0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey)return;event.preventDefault();onNavigate(event.currentTarget.getAttribute('href')!);}}>Read in context →</a></article>)}
      {view!=='english' && <PairedGreek sides={displaySides||[selected.sourceRanges,selected.targetRanges]} edition={selectedEdition} onNavigate={onNavigate}/>}
      <p className="study-help">Connection classifications require an approved review record. Unclassified references remain publisher cross-references.</p>
    </section>}
    
  </>;
  return embedded ? <section className="connections-panel" aria-label="Related NT/OT passages">{content}</section> : <details className="testament-connections" id="testament-connections"><summary>NT/OT connections <span>{loaded ? `(${groups.size})` : ''}</span></summary>{content}</details>;
}
